services:
  reviews:
    build: .
    image: ghcr.io/thanuchcha1603/bookinfo-details:dev
    ports:
      - "8082:9080"
    environment:
      RATINGS_SERVICE: http://ratings:8080/
      STAR_COLOR: black
      ENABLE_RATINGS: true